---
---

## Typical Data Manipulation Functions

| Function    | Returns                                            |
|-------------+----------------------------------------------------|
| `query`    | keep rows that satisfy conditions                  |
| `assign`    | apply a transformation to existing [split] columns |
| `['col1', 'col2']`| select and keep columns with matching names    |
| `inner_join`| merge columns from separate tables into one table  |
| `group_by`  | split data into groups by an existing factor       |
| `group_by.agg` | summarize across rows [and combine split groups]   |

https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_r.html


The table above summarizes the most commonly used functions in
[pandas](){:.rlib}, which we will demonstrate in turn on data from the U.S.
Census Bureau.
{:.notes}

===

### Filter and pattern matching

The `cbp` table includes character `NAICS` column. Of the 2 million
observations, lets see how many observations are left when we keep only the
2-digit NAICS codes, representing high-level sectors of the economy.

```{python lib, message = FALSE, handout = 0}


import pandas as pd

cbp2 = cbp[cbp['NAICS'].str.contains("----")]
cbp2 = cbp2[~cbp2.NAICS.str.contains("-----")]

cbp2.head()


```

Note that a logical we used the function `contains` from pandas to filter the dataset in two steps. The function contains allows for pattern matching of any character within strings. The `~` is used to remove the rows that contains specific patterns.

{:.notes}

===

Filtering string often uses pattern matching by [regular expressions]
which may be a bit more manageable, and streamlines the operations.

```{python message = FALSE, handout = 0}
cbp2 = cbp[cbp['NAICS'].str.contains('[0-9]{2}----')]
cbp2.head()


```

[regular expressions]: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains

===

### Altering, updating and transforming columns

The `assign` function is the [pandas](){:.rlib} answer to updating or altering
your columns. It performs arbitrary operations on existing columns and appends
the result as a new column of the same length.

===

Here's one you've probably needed before:

```{python, handout = 0}
#cbp3["FIPS2"] = cbp3["FIPSTATE"].str.cat(["FIPSCTY"])
cbp2["FIPSTATE"]= cbp2["FIPSTATE"].astype(str)
cbp2["FIPSCTY"]= cbp2["FIPSCTY"].astype(str)

cbp2["FIPS"] = cbp2["FIPSTATE"]+cbp2["FIPSCTY"]
#cbp3.assign(FIPS=cbp3["FIPSTATE"]+cbp3["FIPSCTY"])
cbp2.assign(FIPS2=lambda x: x['FIPSTATE']+x['FIPSCTY'])
#cbp3[["FIPS", "FIPS2","FIPSTATE","FIPSCTY"]].head()

```

===

Multiple arguments to `mutate` produce multiple transformations.

```{python, handout = 0}

cbp2.assign(FIPS2=lambda x: x['FIPSTATE']+x['FIPSCTY'],
            NAICS = cbp2['NAICS'].str.replace('-+',''))
```


===

### Select

To keep particular columns of a data frame (rather than filtering rows), use
the `select` function with arguments that match column names.

```{python}
#names(cbp)
cbp.columns
```

===

One way to "match" is by including complete names, each one you want to keep:

```{python eval = FALSE}
#cbp %>%
#  select(
#    FIPS,
#    NAICS,
#    N1_4, N5_9, N10_19 # a better way?
#  )
  
cbp3 = cbp2[['FIPS','NAICS','N1_4', 'N5_9', 'N10_19']] 
cbp3.head()
```

===

Alternatively, we can use a "select helper" to match patterns.

```{r select, handout = 0}
cbp <- cbp %>%
  select(
    FIPS,
    NAICS,
    starts_with('N')
  )
```
