---
---

## From wide to long

The pandas package’s melt function reshapes “wide” data frames into “long” ones.

```{python, results = 'hide'}
import pandas as pd
import numpy as np
trial_df = pd.DataFrame({"block": [1,2,3],
              "drug": [0.22,0.12,0.42],
              "control": [0.58,0.98,0.19],
              "placebo": [0.31,0.47,0.40]})

trial_df

tidy_trial_df = pd.melt(trial_df,
                  id_vars=['block'],
                  var_name='treatment',
                  value_name='response')
tidy_trial_df

```

All columns, accept for “block”, are stacked in two columns: a “key” and a “value”. The key column gets the name treatment and the value column receives the name response. For each row in the result, the key is taken from the name of the column and the value from the data in the column.

## From long to wide

Data can also fail to be tidy when a table is too long. The Entity-Attribute-Value (EAV) structure common in large databases distributes multiple attributes of a single entity/observation into separate rows.

Remember that the exact state of “tidy” may depend on the analysis: the key is knowing what counts as a complete observation. For example, the community ecology package vegan requires a matrix of species counts, where rows correspond to species and columns to sites. This may seem like too “wide” a format, but in the packages several multi-variate analyses, the abundance of a species across multiple sites is considered a complete observation.

Consider survey data on participant’s age and income stored in a EAV structure.

```{python}

df2 = tidy_trial_df.pivot(index='block',
                          columns='treatment',
                          values='response')
df2 = df2.reset_index()
df2.columns
df2.reset_index()

df2

```

Consider survey data on participant's age and income *stored* in a EAV structure.

```{python}

from pandas.compat import StringIO, BytesIO

text_string = StringIO("""
participant,attr,val
1,age,24
2,age,57
3,age,13
1,income,30
2,income,60
""")

survey_df = pd.read_csv(text_string, sep=",")
survey_df

```

Transform the data with the `pivot` function, which "reverses" a `melt`. These are equivalent to `spread` and `gather` in the dplyr r package.


```{python}
tidy_survey = survey_df.pivot(index='participant',
                          columns='attr',
                          values='val')
print(tidy_survey.head())
tidy_survey = tidy_survey.reset_index()
tidy_survey.columns
tidy_survey.reset_index()

tidy_survey

```

<!-- === -->

<!-- Question -->
<!-- : Why were `attr` and `val` not quoted in the call to `spread`? -->

<!-- Answer -->
<!-- : {:.fragment} They refer to existing column names. In `gather`, quotes are used -->
<!-- to create new column names. -->

<!-- === -->

<!-- One difficulty with EAV tables is the nature of missing data; an entire row -->
<!-- rather than a single cell is missing. Think about what "missing data" could mean -->
<!-- here---perhaps you can supply a value instead of the `NA` in the previous -->
<!-- result. -->

<!-- ```{r, handout = 0} -->
<!-- tidy_survey <- spread(survey, -->
<!--   key = attr, -->
<!--   value = val, -->
<!--   fill = 0) -->
<!-- ``` -->

<!-- === -->

<!-- ```{r} -->
<!-- tidy_survey -->
<!-- ``` -->

